### ISSUE TITLE
Swiper: Items from food/drinks displayed when swiping attractions

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#227] opened 2016-03-10 18:59 UTC
While swiping I saw that there is food in swiping items. 
Online-Thailand-Chiang Mai-Attractons-Swipe.

![image-10-03-16-09-58](https://cloud.githubusercontent.com/assets/16025697/13680828/53c27608-e70b-11e5-84bc-9166110f0895.png)

**Comment by paandahl** [comment] 2016-03-17 06:59
This one happened only when the country is downloaded. Even if you are online, you should mention if the country is downloaded or not (because it makes sense for it to load if from the phone if possible, to save data).

**Comment by NayaMakarova** [comment] 2016-03-17 12:37
It happens when:
country is downloaded and you're online
country is downloaded and you're offline
country isn't downlaoded

**Comment by paandahl** [comment] 2016-03-17 12:39
Tell which region you are on when you go to Attractions, and which
food/drink-item is displayed.

**Comment by paandahl** [comment] 2016-03-17 12:46
It makes a difference if it's a country, city, or neighbourhood. And it's easier for me to reproduce, if I have a concrete example.

**Comment by NayaMakarova** [comment] 2016-03-17 12:57
Ah, sorry, Preben! I read the description of the ''restaurant''. And it's not a restaurant, but cookery school. Stupid Naya. That's why it's in Swipe.

**Comment by paandahl** [comment] 2016-03-17 12:58
Hehe, that's good, because I seemed to think that I fixed it today :p

Ok, let's close this one.

**Closed as completed** 2016-03-17 12:58 UTC
Labels: bug
